"""empty message

Revision ID: 9b7bb651b83f
Revises: 4d17ec5e5d6e
Create Date: 2022-06-16 10:56:09.543758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9b7bb651b83f'
down_revision = '4d17ec5e5d6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pref', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_hobbies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hobby_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('provider_id', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('job', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('born_pref', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('first_pref', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('second_pref', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('third_pref', sa.Integer(), nullable=True))
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('users', 'third_pref')
    op.drop_column('users', 'second_pref')
    op.drop_column('users', 'first_pref')
    op.drop_column('users', 'born_pref')
    op.drop_column('users', 'job')
    op.drop_column('users', 'username')
    op.drop_column('users', 'provider_id')
    op.drop_table('user_hobbies')
    op.drop_table('hobbies')
    op.drop_table('comments')
    # ### end Alembic commands ###
